// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ingredients.sql

package db

import (
	"context"
	"database/sql"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (meal_id, name, quantity, unit, calories, protein, carbs, fats) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) 
RETURNING ingredient_id, meal_id, name, quantity, unit, calories, protein, carbs, fats
`

type CreateIngredientParams struct {
	MealID   sql.NullInt32
	Name     string
	Quantity sql.NullString
	Unit     sql.NullString
	Calories sql.NullString
	Protein  sql.NullString
	Carbs    sql.NullString
	Fats     sql.NullString
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, createIngredient,
		arg.MealID,
		arg.Name,
		arg.Quantity,
		arg.Unit,
		arg.Calories,
		arg.Protein,
		arg.Carbs,
		arg.Fats,
	)
	var i Ingredient
	err := row.Scan(
		&i.IngredientID,
		&i.MealID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.Calories,
		&i.Protein,
		&i.Carbs,
		&i.Fats,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
DELETE FROM ingredients 
WHERE ingredient_id = $1
`

func (q *Queries) DeleteIngredient(ctx context.Context, ingredientID int32) error {
	_, err := q.db.ExecContext(ctx, deleteIngredient, ingredientID)
	return err
}

const getIngredient = `-- name: GetIngredient :one
SELECT ingredient_id, meal_id, name, quantity, unit, calories, protein, carbs, fats 
FROM ingredients 
WHERE ingredient_id = $1
`

func (q *Queries) GetIngredient(ctx context.Context, ingredientID int32) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, getIngredient, ingredientID)
	var i Ingredient
	err := row.Scan(
		&i.IngredientID,
		&i.MealID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.Calories,
		&i.Protein,
		&i.Carbs,
		&i.Fats,
	)
	return i, err
}

const updateIngredient = `-- name: UpdateIngredient :exec
UPDATE ingredients 
SET name = $1, quantity = $2, unit = $3, calories = $4, protein = $5, carbs = $6, fats = $7 
WHERE ingredient_id = $8
`

type UpdateIngredientParams struct {
	Name         string
	Quantity     sql.NullString
	Unit         sql.NullString
	Calories     sql.NullString
	Protein      sql.NullString
	Carbs        sql.NullString
	Fats         sql.NullString
	IngredientID int32
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) error {
	_, err := q.db.ExecContext(ctx, updateIngredient,
		arg.Name,
		arg.Quantity,
		arg.Unit,
		arg.Calories,
		arg.Protein,
		arg.Carbs,
		arg.Fats,
		arg.IngredientID,
	)
	return err
}
