// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: nutrition_goals.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createNutritionGoal = `-- name: CreateNutritionGoal :one
INSERT INTO nutrition_goals (user_id, daily_calories, daily_protein, daily_carbs, daily_fats, start_date, end_date) 
VALUES ($1, $2, $3, $4, $5, $6, $7) 
RETURNING goal_id, user_id, daily_calories, daily_protein, daily_carbs, daily_fats, start_date, end_date
`

type CreateNutritionGoalParams struct {
	UserID        sql.NullInt32
	DailyCalories string
	DailyProtein  sql.NullString
	DailyCarbs    sql.NullString
	DailyFats     sql.NullString
	StartDate     time.Time
	EndDate       sql.NullTime
}

func (q *Queries) CreateNutritionGoal(ctx context.Context, arg CreateNutritionGoalParams) (NutritionGoal, error) {
	row := q.db.QueryRowContext(ctx, createNutritionGoal,
		arg.UserID,
		arg.DailyCalories,
		arg.DailyProtein,
		arg.DailyCarbs,
		arg.DailyFats,
		arg.StartDate,
		arg.EndDate,
	)
	var i NutritionGoal
	err := row.Scan(
		&i.GoalID,
		&i.UserID,
		&i.DailyCalories,
		&i.DailyProtein,
		&i.DailyCarbs,
		&i.DailyFats,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const deleteNutritionGoal = `-- name: DeleteNutritionGoal :exec
DELETE FROM nutrition_goals 
WHERE goal_id = $1
`

func (q *Queries) DeleteNutritionGoal(ctx context.Context, goalID int32) error {
	_, err := q.db.ExecContext(ctx, deleteNutritionGoal, goalID)
	return err
}

const getNutritionGoal = `-- name: GetNutritionGoal :one
SELECT goal_id, user_id, daily_calories, daily_protein, daily_carbs, daily_fats, start_date, end_date 
FROM nutrition_goals 
WHERE goal_id = $1
`

func (q *Queries) GetNutritionGoal(ctx context.Context, goalID int32) (NutritionGoal, error) {
	row := q.db.QueryRowContext(ctx, getNutritionGoal, goalID)
	var i NutritionGoal
	err := row.Scan(
		&i.GoalID,
		&i.UserID,
		&i.DailyCalories,
		&i.DailyProtein,
		&i.DailyCarbs,
		&i.DailyFats,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const updateNutritionGoal = `-- name: UpdateNutritionGoal :exec
UPDATE nutrition_goals 
SET daily_calories = $1, daily_protein = $2, daily_carbs = $3, daily_fats = $4, start_date = $5, end_date = $6 
WHERE goal_id = $7
`

type UpdateNutritionGoalParams struct {
	DailyCalories string
	DailyProtein  sql.NullString
	DailyCarbs    sql.NullString
	DailyFats     sql.NullString
	StartDate     time.Time
	EndDate       sql.NullTime
	GoalID        int32
}

func (q *Queries) UpdateNutritionGoal(ctx context.Context, arg UpdateNutritionGoalParams) error {
	_, err := q.db.ExecContext(ctx, updateNutritionGoal,
		arg.DailyCalories,
		arg.DailyProtein,
		arg.DailyCarbs,
		arg.DailyFats,
		arg.StartDate,
		arg.EndDate,
		arg.GoalID,
	)
	return err
}
