// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Ingredient struct {
	IngredientID int32
	MealID       sql.NullInt32
	Name         string
	Quantity     sql.NullString
	Unit         sql.NullString
	Calories     sql.NullString
	Protein      sql.NullString
	Carbs        sql.NullString
	Fats         sql.NullString
}

type Meal struct {
	MealID        int32
	UserID        sql.NullInt32
	MealTime      time.Time
	MealType      sql.NullString
	Description   sql.NullString
	TotalCalories sql.NullString
	CreatedAt     sql.NullTime
}

type NutritionGoal struct {
	GoalID        int32
	UserID        sql.NullInt32
	DailyCalories string
	DailyProtein  sql.NullString
	DailyCarbs    sql.NullString
	DailyFats     sql.NullString
	StartDate     time.Time
	EndDate       sql.NullTime
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
}
